[project]
name = "clase-dash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash-ag-grid>=32.3.2",
    "dash[async]>=3.2.0",
    "httpx>=0.28.1",
    "pandas>=2.3.3",
]
